In [1]:
import data
import utility as ut

In [5]:
fold, max_fold = 1, 5
for fold in range(1,6):
    data_range_npd = [(0,90), (91,140), (141,289)]#parts of the new ext parkinson dataset to be used
    sp_pd = ut.get_split_ranges(data_range_npd,fold,max_fold)
    r_pd = sp_pd["train"]
    s_pd = sp_pd["val"]
    print("Fold:", fold)
    print("Train chunk:", r_pd)
    print("Valdn chunk:", s_pd)
    

Fold: 1
Train chunk: [(19, 36), (37, 54), (55, 72), (73, 90), (101, 110), (111, 120), (121, 130), (131, 140), (171, 200), (201, 230), (231, 260), (261, 289)]
Valdn chunk: [(0, 18), (91, 100), (141, 170)]
Fold: 2
Train chunk: [(0, 18), (37, 54), (55, 72), (73, 90), (91, 100), (111, 120), (121, 130), (131, 140), (141, 170), (201, 230), (231, 260), (261, 289)]
Valdn chunk: [(19, 36), (101, 110), (171, 200)]
Fold: 3
Train chunk: [(0, 18), (19, 36), (55, 72), (73, 90), (91, 100), (101, 110), (121, 130), (131, 140), (141, 170), (171, 200), (231, 260), (261, 289)]
Valdn chunk: [(37, 54), (111, 120), (201, 230)]
Fold: 4
Train chunk: [(0, 18), (19, 36), (37, 54), (73, 90), (91, 100), (101, 110), (111, 120), (131, 140), (141, 170), (171, 200), (201, 230), (261, 289)]
Valdn chunk: [(55, 72), (121, 130), (231, 260)]
Fold: 5
Train chunk: [(0, 18), (19, 36), (37, 54), (55, 72), (91, 100), (101, 110), (111, 120), (121, 130), (141, 170), (171, 200), (201, 230), (231, 260)]
Valdn chunk: [(73, 90), (131

In [9]:
batch = 10
print(batch)
for batch in range(10):
    print(batch)
print("Batch", batch)

10
0
1
2
3
4
5
6
7
8
9
Batch 9


In [11]:
ut.get_array_info(data.get_newext_dev_parkinson_cls_data()[0], "New EXT Dev Data")

----------
New EXT Dev Data specifications:
<class 'numpy.ndarray'>
(290, 95, 69, 79, 1)
float32
Mean 0.521783
Median 0.448994
Max 2.54515
Min -0.0328023
std.dev. 0.426738
----------


In [16]:
import numpy as np
fq = np.sum(data.get_newext_dev_parkinson_cls_data()[1],axis=0 )
sm = np.sum(fq)
wts = np.square(sm/fq)

In [23]:
wts[:,0]

array([ 10.15577793,  33.6400032 ,   3.78811765], dtype=float32)

In [19]:
wt2 = np.sum(fq*fq)/(fq*fq)
wt2

array([[  3.98285222],
       [ 13.19279957],
       [  1.4856087 ]], dtype=float32)

In [21]:
fq
fq*fq

array([[  8281.],
       [  2500.],
       [ 22201.]], dtype=float32)

In [24]:
import data
import numpy as np

In [25]:
X, Y = data.get_newext_dev_parkinson_cls_data()
Z, = data.get_newext_test_parkinson_cls_data()

In [45]:
ut.get_array_info(X)
ut.get_array_info(Z)


----------
Array specifications:
<class 'numpy.ndarray'>
(290, 95, 69, 79, 1)
float32
Mean 0.521783
Median 0.448994
Max 2.54515
Min -0.0328023
std.dev. 0.426738
----------
----------
Array specifications:
<class 'numpy.ndarray'>
(108, 95, 69, 79, 1)
float32
Mean 0.518901
Median 0.438323
Max 1.84031
Min 0.0
std.dev. 0.425261
----------


In [48]:
X1 = X[0,:,:,:,0]
num_pix_mx = np.where(X>1.84030)
num_pix_mn = np.where(X<0)
print(num_pix_mx[0].shape[0])
print(num_pix_mn[0].shape[0])

1179
10572


In [50]:
X_clipped = np.clip(X, 0,1.84031 )
num_pix_mx = np.where(X_clipped>1.84030)
num_pix_mn = np.where(X_clipped<0)
print(num_pix_mx[0].shape[0])
print(num_pix_mn[0].shape[0])

1179
0
